-- creating census table
DROP TABLE IF EXISTS census_table;
CREATE TABLE census_table (
	CENSUS_YEAR INTEGER, 
  	DGUID VARCHAR(250) PRIMARY KEY NOT NULL,
	GEO_LEVEL VARCHAR(250),
	GEO_NAME VARCHAR(250),
	TNR_SF INTEGER,
	TNR_LF INTEGER,
	DATA_QUALITY_FLAG INTEGER,
	CHARACTERISTIC_ID INTEGER,
	CHARACTERISTIC_NAME VARCHAR(250) ,
	CHARACTERISTIC_NOTE INTEGER,
	C1_COUNT_TOTAL INTEGER,
	
	"C2_COUNT_MEN+" INTEGER,

	"C3_COUNT_WOMEN+" INTEGER,
	
	C4_COUNT_LOW_CI_TOTAL INTEGER,
	
	"C5_COUNT_LOW_CI_MEN+" INTEGER,
	
	"C6_COUNT_LOW_CI_WOMEN+" INTEGER,

	C7_COUNT_HI_CI_TOTAL INTEGER,

	"C8_COUNT_HI_CI_MEN+" INTEGER,
	
	"C9_COUNT_HI_CI_WOMEN+" INTEGER,
	
	C10_RATE_TOTAL INTEGER,

	"C11_RATE_MEN+" INTEGER,
	
	"C12_RATE_WOMEN+" INTEGER,
	
	C13_RATE_LOW_CI_TOTAL INTEGER,
	
	"C14_RATE_LOW_CI_MEN+" INTEGER,
	
	"C15_RATE_LOW_CI_WOMEN+" INTEGER,
	
	C16_RATE_HI_CI_TOTAL INTEGER,
	
	"C17_RATE_HI_CI_MEN+" INTEGER,
	
	"C18_RATE_HI_CI_WOMEN+" INTEGER
	
	);

SELECT * FROM census_table